LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_USES_XIAOMI_MITHORIUM_COMMON_TREE),true)

KERNEL_OUT := $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/
KERNEL_HEADERS_INSTALL := $(KERNEL_OUT)/usr

$(KERNEL_OUT):
	mkdir -p $(KERNEL_OUT)

$(KERNEL_HEADERS_INSTALL): $(KERNEL_OUT)
	cp -Rf $(LOCAL_PATH)/$(TARGET_DEVICE)/kernel_headers $(KERNEL_HEADERS_INSTALL)

endif
